# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Jaume Fonte Cano
title: Programador Unity
email: jaume.fonte@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: jaumefonte
github_username:  jaumefonte
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: jaumefonte
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Información sobre mí.
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, me llamo Jaume y soy programador de videojuegos. He trabajado en varios juegos para PC y móviles Android. También he hecho ports para Playstation4 y Nintendo Switch.

#  #I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experiencia

# Education Section
education_title: Educación

# More Section
more_title: Otros Conocimientos.
more_content: | # this will include new lines to allow paragraphs    
     - Mi experiencia en producción audiovisual incluye cortometrajes, largometrajes, series, realities y espectaculos en directo ara televisión, donde mi trabajo consistía en analizar y gestionar los recursos necesarios para el desarrollo del flujo de trabajo entre los distintos equipos.
     - Programación de aplicaciones de escritorio en C# 
     - Gestión de versiones con Git
     - Scrum/Kanban
     - Python
     - Linux

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   sass_dir: _sass
#   style: compressed

plugins:
 - jekyll-seo-tag

repository: jaumefonte/jaumefonte.github.io
